spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: coinmonitorhub
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          charset: UTF
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${LOGIN_USERNAME}
      password: ${LOGIN_PASSWORD}

server:
  port: 8080

logging:
  level:
    com.projects.coin_monitor_hub: DEBUG

coin:
  gecko:
    api:
      key: ${COIN_GECKO_API_KEY}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

personal:
  phone-number: ${PERSONAL_PHONE_NUMBER}
