database: mysql

spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    gcp:
      sql:
        database-name: ${MYSQL_DATABASE_NAME}
        instance-connection-name: ${MYSQL_INSTANCE_CONNECTION_NAME}

  # Initialize the database since the newly created Cloud SQL database has no tables. The following flag is for Spring Boot 2.5+.
  sql:
    init:
      mode: always

