spring:
  config:
    import: file:env.properties
  application:
    name: coinmonitorhub
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          charset: UTF

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    com.projects.coin_monitor_hub: DEBUG

coin:
  gecko:
    api:
      key: ${COIN_GECKO_API_KEY}